<?php
return [
    '2022' => [

        '1ª Reunião pedagógica' => 'https://drive.google.com/drive/folders/1En01WuaFZr1toWajHbp1j-98sHQ6xI3S',
        'Ação casa idoso' => 'https://drive.google.com/drive/folders/1YiDiZK26Y8sApDeVsyp2733HpNUdCFVc',
        'Aula Magna' => 'https://drive.google.com/drive/folders/1IY275FrWYdWo1-qZ836q1hCdcAgPqAqJ',
        'Cerimônia do jaleco' => 'https://drive.google.com/drive/folders/1uLl3_fgHRjYRYWt4ynuVGG-htx9MEqSM',
        'Colação de grau Ad e CTB' => 'https://drive.google.com/drive/folders/1RoWw9xE4BA5B3UfWmhRu0o-itTKgtHnS',
        'Confraternização' => 'https://drive.google.com/drive/folders/1X-k_WiZbPuFOb1XW4VoTQnFy6bshMDqA',
        'Debate das turmas 103 e 104 - Ética profissional' => 'https://drive.google.com/drive/folders/1QzuntFbRN-aJBF2HLQRtMTpjKD947Xo1',
        'FACX DAY' => 'https://drive.google.com/drive/folders/1QzRgJJhV9ImKstqzLpi9jMpCdP0GSirY',
        'Jornada acadêmica' => 'https://drive.google.com/drive/folders/1wzCWMXQdQPVNg3zSikiAK2rEs8-0ZlJ2',
        'Palestra - Gestão financeira' => 'https://drive.google.com/drive/folders/1ypXmkt1PPg3sxa5goTE2TWj8KEVb40Rq',
        'Palestra PÓS obstetrícia' => 'https://drive.google.com/drive/folders/1B5-zmQNoYL9DU9eG9Jo3_z-eQgCxhiH0',
        'Semana cultural' => 'https://drive.google.com/drive/folders/17VEb1rboOA2mgxpKFJ5hsHMMnTdv7Ic8',
        'Seminário integrador - ADM' => 'https://drive.google.com/drive/folders/1196Oz_l6v1R5zxkx0Im_9M876DNjhM4R',
        'Seminário integrador - CTB' => 'https://drive.google.com/drive/folders/11AnuBVwqLEkyUSj2XSXaM98cALa7oSK2',
        'Seminário integrador - ENF - Novembro Azul' => 'https://drive.google.com/drive/folders/1ji4j1I4zIL3Az1SOoHK1L5wl7cpNsfQ0',
        'Seminário integrador - ENF - Outibro Rosa' => 'https://drive.google.com/drive/folders/1khfj9Tv_J0wbXTRNSu-Q_x7eSKJ501Mi',

    ],
    '2023' => [

        '1ª Reunião pedagógica - Início do semestre letivo' => 'https://drive.google.com/drive/folders/1bXRGENkxeBY-aNeUmyACXPJqOijpUwC0',
        '2ª Reunião pedagógica - Final do semestre letivo' => 'https://drive.google.com/drive/folders/1j7-70KrjJzv2K3IzgPGakr5aM7Q9hMIe',
        'Atlética' => 'https://drive.google.com/drive/folders/1_-R78XZmePh9lWXJL7oBTKX8O8t7tHDh',
        'Capacitação pedagógica' => 'https://drive.google.com/drive/folders/1yxuypf5rXqe30gYh2wrO7S7p47jU8bnW',
        'Dia internacional da mulher' => 'https://drive.google.com/drive/folders/1ujeHUQu8ZQl8yHQvJ6BBj5f1d8R_TAoY',
        'Mesa redonda-ADM' => 'https://drive.google.com/drive/folders/1QFTy9E6GfnamyeVEguDBMSpBJ1Pnk2Uz',
        'Palestra violência obstétrica - Direitos da mulher no parto' => 'https://drive.google.com/drive/folders/18ef9bhWum7IaSNKltFam7iRfFrQU3Ubz',
        'Renovações de REC ADM' => 'https://drive.google.com/drive/folders/11cnAWxkPPuEh5ZZlXKNry8KZ8SCbG13j',
        'Renovações de REC CTB' => 'https://drive.google.com/drive/folders/1o-SDvKkZ4si8fKPBHmNXGEWzH7W9dYRT',
        'Semana da enfermagem-HRPT' => 'https://drive.google.com/drive/folders/11IlUL9_auoUoZ7dGv6I3kdcdPdgSeNwz',
        'Seminário integrador - ADM' => 'https://drive.google.com/drive/folders/1FS-rM2B6NpJt6Q5zXAo0XMTOr56h9j2c',
        'Seminário integrador - CTB' => 'https://drive.google.com/drive/folders/1O6hiHRHskWV7wjDLWQvzwLGvDjoIu9Tp',
        'Seminário integrador - ENF' => 'https://drive.google.com/drive/folders/1cgovZHqXb2JuIgqhWTKNkMhRf927G2M2',
        'Palestra Mulheres' => 'https://drive.google.com/drive/folders/1gzr6YezUu9Jp6DQcC-wte2s-CQ4FvEvN',
        'Ação extensionista de Promoção da Saúde em Vitória do Xingu' => 'https://drive.google.com/drive/folders/1Iq1LhE4L48lONbxCSg2c8LholvxTOlWg',
        'Aula inaugural' => 'https://drive.google.com/drive/folders/1sILhacCCtaW5wdISrPnr0H99sUCJS7o8',
        'Cerimônia do Jaleco' => 'https://drive.google.com/drive/folders/1-Qaw7S2j8irTXRgUsk5cKFLCMgH9HCWR',
        'Confraternização FACX' => 'https://drive.google.com/drive/folders/1kzI5CgyMq2qx48zKNMnuRgF9S4T6Atcl',
        'Dia do Administrador - Empreendedorismo e Liderança, Trilhando o caminho do sucesso profissional' => 'https://drive.google.com/drive/folders/1Qs2-RLHraqSTtQ6JGv-Csjso5buBRtoL',
        'Dia do Advogado' => 'https://drive.google.com/drive/folders/1iUPsJmP1LJ1vw29aL0D9bs6SN9OcLr26',
        'Dia do Contador - Palestra sobre Reforma Tributária' => 'https://drive.google.com/drive/folders/1NbVnPK0v2kyK6rZkG64va9Pj09oz_hMb',
        'Formação Docente' => 'https://drive.google.com/drive/folders/11FKksx01u7KxbaPoIFJZspIaI8490f2q',
        'Outubro Rosa' => 'https://drive.google.com/drive/folders/1ONECleU8ERxUu9cWufRtWRdHWSo34sKb',
        'Outubro Rosa - Parceria Sicredi' => 'https://drive.google.com/drive/folders/17EM9Y6LU5nRLCsq2EjhhUg4Eu-8EnYp1',
        'Palestra com o promotor - Luciano Augusto Araujo da Costa' => 'https://drive.google.com/drive/folders/1-LyOHtyF_4huT1In6kMQikxNZ1IZ23Lf',
        'Palestra sobre instituições financeiras no Brasil' => 'https://drive.google.com/drive/folders/1J1aXLoKG5Gb15uzzdVFBugX6IBd6J46o',
        'Palestra TCE Cidadão' => 'https://drive.google.com/drive/folders/1GJSoa300SBBqeM4Vn6AMFNuxYTfiXQiG',
        'Reunião Pedagógica' => 'https://drive.google.com/drive/folders/1BmYNT7ZVmPHu3rMAqhobuE3qU_yZNzr9',
        'Setembro Amarelo - FACX' => 'https://drive.google.com/drive/folders/1LtwNCAawA6i1_6U-k3yBsExWgkIKOQqB',
        'Setembro Amarelo - Liga - Centro de Eventos' => 'https://drive.google.com/drive/folders/1yphDujOtMgy52s_Qh3b2hSTw6R6je6N7',
        'Setembro Amarelo - Cuida de quem cuida' => 'https://drive.google.com/drive/folders/1nrmS0Eyv6_MYFRrZoZjypDnF-r9BbImB',
        'Simulado ENADE' => 'https://drive.google.com/drive/folders/1Y44XZJOyKCBZIhJcsS1PNQATt7rMzxzU',
        'Visita Belo Monte- ADM e CTB' => 'https://drive.google.com/drive/folders/10ya_lSqWzR3QeY5LyyF6xtCrNL0-KA3N',

    ],
    '2024' => [

        'Aniversariantes Fevereiro' => 'https://drive.google.com/drive/folders/1wIqG1bv-bhR-6dSTAc9VrxjV3YHIlPA5',
        'Aula inaugural' => 'https://drive.google.com/drive/folders/1UhBwpn7RONBpDUxDYg3zRfom-QT77Sj7',
        'Capacitação libras' => 'https://drive.google.com/drive/folders/1SmPBKzvWc-zoJ_ahotw7zzimEb4I-A5J',
        'Capacitação planos de ensino e plano de aulas práticas' => 'https://drive.google.com/drive/folders/1_uP3WhpNeDCN3n8UFtBbr3Owwch9EFrh',
        'Cerimônia do jaleco' => 'https://drive.google.com/drive/folders/1FwnjGX4XK06l9ihfIKlVrPsyze1gYRaK',
        'Defesa TCC ADM e CTB' => 'https://drive.google.com/drive/folders/1HxJlTva-67ZZFb03Td09557wryxPMsOa',
        'Entrega monitoria' => 'https://drive.google.com/drive/folders/1tC_Pqo-8rMFHlvG4CCeSbTyCBO3oUaAk',
        'Exposição acadêmica de enfermagem' => 'https://drive.google.com/drive/folders/1974IMXSS2BqfMUf7_Uh_ukRj273zVIIb',
        'FACX na comunidade 2024.1' => 'https://drive.google.com/drive/folders/1JNn8QXre0CNF8RCFkNIsIxCM39cHXc7q',
        'Formatura CTB – ADM' => 'https://drive.google.com/drive/folders/1dOHsRFMROAIRNaTdbExBu2Hre7D_aI5g',
        'Oficina preparatória para estágio com a OAB universitária-Direito' => 'https://drive.google.com/drive/folders/1dVZ4TN9IgUxJmQ11qPzzj9dp-sQZGRc_',
        'Palestra penhas não se calem' => 'https://drive.google.com/drive/folders/11Ju99phgy66AFiQwTZ18HGsCq3Z8lmZL',
        'Palestra sobre a importância da língua portuguesa-Direito' => 'https://drive.google.com/drive/folders/1zFlVMg0gH4QGV2fbJyJx-MCYJEN475u2',
        'Roda de conversa turmas 1º enfermagem' => 'https://drive.google.com/drive/folders/1452DT8LmvG1wXrFlHGHcbXmoVsjOs2DE',
        'Semana de enfermagem 2024-Dia 1' => 'https://drive.google.com/drive/folders/1oHaULzfqNFp5FBo6Pvk41qsgHwiBBAcz',
        'Semana de enfermagem 2024-Dia 2' => 'https://drive.google.com/drive/folders/1luB02kzW0L-LcvJlWAV4cVr0ZcMs50Oo',
        'VadMecun' => 'https://drive.google.com/drive/folders/1ffgI_wnKxzuTHDgcLPqq50L2L1rnpMBZ',
        'Visitas e ações externas enfermagem' => 'https://drive.google.com/drive/folders/1RYNwFAintx7SV5n6GCUZkuAXnCJkAv5M',
        'Word Criative Day' => 'https://drive.google.com/drive/folders/1nCgff-Nkx27mzb0YL_3zo4RhjSeAfT3L',
        'Colação de Grau Gabinete ADM e CTB' => 'https://drive.google.com/drive/u/0/folders/1phgubpEyLWWThhms6-iGOFJyjxfpfNBu',
        'Comemoração dia Administrador e Contador' => 'https://drive.google.com/drive/u/0/folders/1r4xXm7bxBRK1hCIoo6DmtQdCrItlmdfu',
        'Retorno 2024.2' => 'https://drive.google.com/drive/u/0/folders/1rzYFC74IA50PxgHrTzf5XOWq-K0BqOYs',
        'Evento Setembro Amarelo' => 'https://drive.google.com/drive/u/0/folders/1imfBluFSvFWIeYpHURxGySlBA89C-HEm',
        'Retorno 2024.2 -Aula inaugural' => 'https://drive.google.com/drive/u/0/folders/1i0UmvRO4zlGvAhFqnqV_xPIuGs666zO2',
        'II - Interclasse Enfurecida FACX 2024' => 'https://drive.google.com/drive/u/0/folders/1MIf3ia2Tp7Xw5KiEfZ3mBpvi6PTR9eTi',
        'Outubro Rosa ACIAPA - Adm e Ctb' => 'https://drive.google.com/drive/u/0/folders/1dr3KrT7craKjCYGnqpLO7g8rNrfjDWia',
        'Reunião Inicial DOCENTES' => 'https://drive.google.com/drive/u/0/folders/16TR_GGM8S1JBt4Q5ftNvyzP7ogVJhMsN',
        'Capacitação a alunos do ensino médio- ADM 17-10-2024' => 'https://drive.google.com/drive/folders/1CohoqDmIcTt_HtCdKQcHqv5oClVyoEab?hl=pt-br',
        'Ação ENFURECIDA Crianças 2024' => 'https://drive.google.com/drive/folders/1APKkdwngY05Qoq0Y6nGa9yEIQQPHrND6',
        'Projeto de extensão - Envelhecer' => 'https://drive.google.com/drive/folders/1FncJGN7jRzoFRa8pSnaiNRfePx25V9Qe',
        'Projeto de extensão - Enfermagem HGA' => 'https://drive.google.com/drive/folders/1KyxfbYdOi_es7E_tS7POCIg-TM-lgS5G',
        'Projeto de extensão - Casa da Sabedoria' => 'https://drive.google.com/drive/folders/1Y1C0HSfdPS0TVUeagTkHCmaZYTtANy1G',
        'Projeto de extensão - Orla da Cidade' => 'https://drive.google.com/drive/folders/1Ykg44Uefg6gg_kk254d6kTr8gRwuRTxg',
        'Projeto de extensão - Enfermagem Getulio' => 'https://drive.google.com/drive/folders/1RxmZkwiAu16FLB8qs4xfqznW7zUs7Koa',
        'Projeto de extensão - Maria de Farias' => 'https://drive.google.com/drive/folders/1qkXdyCsfYzwQZMnPd6-8i66X4RT7XpqD',
        'Projeto de extensão - Adm e CTB' => 'https://drive.google.com/drive/folders/1mba-jVclMZS7jkMgD-DlpC7TKsWypUtC',
        'Projeto de extensão - Direito' => 'https://drive.google.com/drive/folders/1X3D-oNSuj0CjEDcOtnk-dDhvUR-6SXGd',
        'Cerimônia do jaleco 2' => 'https://drive.google.com/drive/folders/1XIHJCeZmK9yNvB85Q7zN_K2p5ClHAdSV',
        'VadMecun 2' => 'https://drive.google.com/drive/folders/1jvLWd2WEYZfHrDB6XJpuDGqltwyY1OfQ',
    ],

    '2025' => [

        'Minicurso Acadweb' => 'https://drive.google.com/drive/folders/1nWX24yf0iMNKTAdVGBtCjeL_camewMf8',
        'Aula Inaugural' => 'https://drive.google.com/drive/folders/14oV0dxl4qdF6w74TK0lqqVFDF8Pnsr88',
        'Reunião Docentes' => 'https://drive.google.com/drive/folders/1O-QybSAxmnOMK4CC-enyP2wl84CHIRIz',
        'Seminário de Inequidades' => 'https://drive.google.com/drive/folders/1zA2cKixLZqs9aBRDf3Y5gOmYJoBx_i-V',
        'Formatura Ctb e ADM' => 'https://drive.google.com/drive/folders/1WixoWB9qiwfvDuzGQe_2ldXb_irdkAM4',
    ],
];
